name: ${name}
version: ${version}
main: org.LegendaryHardcore.legendaryonboarding.paper.PaperLegendaryOnboarding
api-version: '1.21'
authors: [Natonite, Thowan]

commands:
  accept:
    description: Accept the server rules
    usage: /accept
    permission: legendaryonboarding.accept
  legendaryonboarding:
    description: Manage LegendaryOnboarding
    usage: /legendaryonboarding reload
    aliases: [lo]
    permission: legendaryonboarding.reload

permissions:
  legendaryonboarding.accept:
    default: true
  legendaryonboarding.reload:
    default: op
