name: ${name}
version: ${version}
main: org.LegendaryHardcore.legendaryonboarding.paper.PaperLegendaryOnboarding
api-version: '1.21'
authors: [Natonite, Thowan]
loadbefore: [TabCompleteFilter, DiscordSRV]
softdepend: [ChatControl, ChatControlRed]

commands:
  accept:
    description: Accept the server rules
    usage: /accept
    permission: legendaryonboarding.accept
  legendaryonboarding:
    description: Manage LegendaryOnboarding
    usage: /legendaryonboarding <help | reload | status | debug>
    aliases: [lo]

permissions:
  legendaryonboarding.accept:
    default: true
  legendaryonboarding.reload:
    default: op
  legendaryonboarding.status:
    default: op
  legendaryonboarding.debug:
    default: op
